import { contextBridge, ipcRenderer } from "electron";

/*
 * The only bridge between the screens and the machine.
 *
 * Deliberately a list, not a pipe. Everything the renderer can do is written
 * here by name, so what the interface is able to reach is one file long and
 * can be read in a few minutes. There is no call that takes a channel name
 * or a file path from the screen.
 */
const invoke = (channel: string) => (...args: unknown[]) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld("ouaqt", {
  readConfiguration: invoke("configuration:read"),
  readPreferences: invoke("prefs:read"),
  licenceSerial: invoke("licence:serial"),
  openPayment: invoke("open:pay"),
  payHelp: invoke("licence:payHelp"),
  checkLicence: invoke("licence:check"),
  writePreferences: invoke("prefs:write"),
  databaseState: invoke("database:state"),

  products: invoke("products:list"),
  productDetail: invoke("products:detail"),
  addProduct: invoke("products:add"),
  updateProduct: invoke("products:update"),
  archiveProduct: invoke("products:archive"),
  importProducts: invoke("products:import"),
  receiveStock: invoke("stock:receive"),
  adjustStock: invoke("stock:adjust"),
  stockOverview: invoke("stock:overview"),
  stockFlags: invoke("stock:flags"),

  recordSale: invoke("sales:record"),
  paymentApps: invoke("payapps:list"),
  addPaymentApp: invoke("payapps:add"),
  renamePaymentApp: invoke("payapps:rename"),
  setPaymentAppLogo: invoke("payapps:logo"),
  removePaymentApp: invoke("payapps:remove"),
  movePaymentApp: invoke("payapps:move"),
  columns: invoke("columns:list"),
  addColumn: invoke("columns:add"),
  renameColumn: invoke("columns:rename"),
  hideColumn: invoke("columns:hide"),
  setColumnChoices: invoke("columns:choices"),
  moveColumn: invoke("columns:move"),
  deleteColumn: invoke("columns:delete"),
  setColumnValue: invoke("columns:value"),
  exportList: invoke("lists:export"),
  printList: invoke("lists:print"),
  pastExpiry: invoke("sales:pastExpiry"),
  recentSales: invoke("sales:recent"),
  voidSale: invoke("sales:void"),
  saleDetail: invoke("sales:detail"),
  salesBetween: invoke("sales:between"),

  customers: invoke("customers:list"),
  customerDetail: invoke("customers:detail"),
  addCustomer: invoke("customers:add"),
  updateCustomer: invoke("customers:update"),
  recordPayment: invoke("customers:pay"),

  cashCurrent: invoke("cash:current"),
  cashHistory: invoke("cash:history"),
  cashOpen: invoke("cash:open"),
  cashClose: invoke("cash:close"),

  reportSummary: invoke("reports:summary"),
  reportTop: invoke("reports:top"),
  reportPastExpiry: invoke("reports:pastExpiry"),
  reportExport: invoke("reports:export"),
  trialSummary: invoke("reports:trial"),
  dailyTotals: invoke("reports:daily"),
  recentAudit: invoke("audit:recent"),
  auditBetween: invoke("audit:between"),
  staffList: invoke("staff:list"),

  printSettings: invoke("print:settings"),
  savePrintSettings: invoke("print:save"),
  printers: invoke("print:printers"),
  printReceipt: invoke("print:receipt"),
  printTest: invoke("print:test"),

  backupInfo: invoke("backup:info"),
  backupSave: invoke("backup:save"),
  backupPick: invoke("backup:pick"),
  backupRestore: invoke("backup:restore"),

  /* The trades' own screens: see ipc-trades.ts. */
  cashbookAdd: invoke("cashbook:add"),
  cashbookBetween: invoke("cashbook:between"),
  openOrders: invoke("orders:open"),
  getOrder: invoke("orders:get"),
  startOrder: invoke("orders:start"),
  addToOrder: invoke("orders:add"),
  changeOrderLine: invoke("orders:change"),
  moveOrder: invoke("orders:move"),
  cancelOrder: invoke("orders:cancel"),
  sendToKitchen: invoke("orders:send"),
  printBill: invoke("orders:bill"),
  payOrder: invoke("orders:pay"),
  updateOrder: invoke("orders:update"),
  setLineNote: invoke("orders:note"),
  servicesBetween: invoke("orders:services"),
  reopenSale: invoke("sales:reopen"),
  accountPeriods: invoke("accounts:periods"),
  accountStatement: invoke("accounts:statement"),
  accountStatus: invoke("accounts:status"),
  receiptPdf: invoke("print:receiptPdf"),
  receiptHtml: invoke("print:receiptHtml"),
  bakeryDay: invoke("bakery:day"),
  recordProduction: invoke("bakery:produce"),
  recordUnsold: invoke("bakery:unsold"),
  preorders: invoke("preorders:list"),
  createPreorder: invoke("preorders:create"),
  preorderReady: invoke("preorders:ready"),
  collectPreorder: invoke("preorders:collect"),
  cancelPreorder: invoke("preorders:cancel"),
  printPreorder: invoke("preorders:print"),
  locations: invoke("locations:list"),
  addLocation: invoke("locations:add"),
  renameLocation: invoke("locations:rename"),
  stockByLocation: invoke("stock:byLocation"),
  transfer: invoke("stock:transfer"),
  dispatch: invoke("dispatch:send"),
  dispatchesBetween: invoke("dispatch:between"),
  printDispatch: invoke("dispatch:print"),
  warehouseFlows: invoke("warehouse:flows"),
  warehouseJournal: invoke("warehouse:journal"),
  rooms: invoke("rooms:list"),
  addRoom: invoke("rooms:add"),
  updateRoom: invoke("rooms:update"),
  setRoomStatus: invoke("rooms:status"),
  roomIssues: invoke("rooms:issues"),
  reportIssue: invoke("rooms:report"),
  resolveIssue: invoke("rooms:resolve"),
  stayLines: invoke("stays:lines"),
  editStay: invoke("stays:edit"),
  stays: invoke("stays:list"),
  getStay: invoke("stays:get"),
  bookStay: invoke("stays:book"),
  checkIn: invoke("stays:checkIn"),
  addAdvance: invoke("stays:advance"),
  addCharge: invoke("stays:charge"),
  folio: invoke("stays:folio"),
  checkOut: invoke("stays:checkOut"),
  cancelStay: invoke("stays:cancel"),
  printFolio: invoke("stays:print"),
  occupancy: invoke("hotel:occupancy"),
  routes: invoke("routes:list"),
  addRoute: invoke("routes:add"),
  updateRoute: invoke("routes:update"),
  vehicles: invoke("vehicles:list"),
  addVehicle: invoke("vehicles:add"),
  tripsBetween: invoke("trips:between"),
  tripDetail: invoke("trips:detail"),
  scheduleTrip: invoke("trips:schedule"),
  setTripStatus: invoke("trips:status"),
  printManifest: invoke("trips:manifest"),
  sellTicket: invoke("tickets:sell"),
  boardTicket: invoke("tickets:board"),
  cancelTicket: invoke("tickets:cancel"),
  parcels: invoke("parcels:list"),
  registerParcel: invoke("parcels:register"),
  loadParcel: invoke("parcels:load"),
  parcelArrived: invoke("parcels:arrived"),
  deliverParcel: invoke("parcels:deliver"),
  cancelParcel: invoke("parcels:cancel"),
  printParcel: invoke("parcels:print"),
  routeTakings: invoke("transport:takings"),

  appInfo: invoke("app:info"),
  licenceState: invoke("licence:state"),
  activate: invoke("licence:activate"),
  activateNearby: invoke("licence:nearby"),
  /* The result of an activation that arrived through the ouaqt:// link. */
  onActivated: (handler: (result: unknown) => void) => {
    const listener = (_event: unknown, result: unknown) => handler(result);
    ipcRenderer.on("licence:activated", listener);
    return () => ipcRenderer.removeListener("licence:activated", listener);
  },
  openWhatsapp: invoke("open:whatsapp"),
  /* A new version has downloaded and will install when the app is closed. */
  onUpdateReady: (handler: (info: { version: string }) => void) => {
    const listener = (_event: unknown, info: { version: string }) => handler(info);
    ipcRenderer.on("update:ready", listener);
    return () => ipcRenderer.removeListener("update:ready", listener);
  },
});
